//go:build windows

package config

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// This piece of code is generated by ChatGPT
func PlatformInstaller(inst *Installer) error {
	switch inst.Executable {
	case "powershell":
		return runScript("powershell.exe", ".ps1", inst.InstallScript, "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-File")
	case "cmd.exe":
		return runScript("cmd.exe", ".bat", inst.InstallScript, "/C")
	default:
		return fmt.Errorf("unsupported executable: %s", inst.Executable)
	}
}

func runScript(exe, ext, body string, argsPrefix ...string) error {
	f := filepath.Join(os.TempDir(), "installer"+ext)
	if err := os.WriteFile(f, []byte(body), 0600); err != nil {
		return err
	}

	args := append(argsPrefix, f)

	cmd := exec.Command(exe, args...)

	output, err := cmd.CombinedOutput()

	if err != nil {
		return err
	}

	fmt.Println(string(output))

	return nil
}
